import {Activity,ArrowRight,BarChart3,CheckCircle2,Clock3,DatabaseZap,Download,Mail,Newspaper,ShieldCheck,Smartphone,TriangleAlert,Utensils,UsersRound} from "lucide-react";
import Link from "next/link";
import {SetupNotice} from "@/components/page-primitives";
import {getOverviewData,type OverviewMetric} from "@/lib/overview-data";

export const dynamic="force-dynamic";

export default async function OverviewPage(){
  const data=await getOverviewData();
  const refreshed=data.refreshedAt?new Date(data.refreshedAt).toLocaleString("en-US",{dateStyle:"medium",timeStyle:"short",timeZone:data.timezone}):"Not connected";
  return <div className="space-y-8 pb-10">
    <header className="relative overflow-hidden rounded-3xl border border-[#cfe2f6] bg-gradient-to-br from-[#032254] via-[#0a3b78] to-[#0c67c9] px-6 py-7 text-white shadow-[0_14px_40px_rgba(3,34,84,.18)] md:px-8 md:py-8"><div className="pointer-events-none absolute -right-12 -top-24 size-72 rounded-full bg-cyan/20 blur-3xl"/><div className="relative flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="mb-2 text-xs font-bold uppercase tracking-[.16em] text-cyan-100">GO command center</p><h1 className="text-2xl font-bold tracking-tight sm:text-3xl">Overview</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-blue-100">One calm view of how people discover GO, engage with GoWash and GoCarry, read GO stories, and join the newsletter.</p></div><div className="rounded-2xl border border-white/15 bg-white/10 px-4 py-3 text-xs text-blue-100 backdrop-blur"><span className="block font-semibold text-white">30-day operating window</span><span className="mt-1 block">{data.timezone} · Refreshed {refreshed}</span></div></div></header>
    {data.status==="unconfigured"&&<SetupNotice issues={["Configure Supabase in apps/admin/.env.local to load live GO aggregates."]}/>} {data.status==="unauthenticated"&&<SetupNotice issues={["Sign in with an active GO workspace membership to load live aggregates."]}/>} {data.status==="unavailable"&&<SetupNotice issues={["The GO data service could not be reached. No placeholder values were substituted."]}/>} {data.status==="empty"&&<SetupNotice issues={["The GO data connection is available, but no aggregate events have been recorded for this window yet."]}/>} 
    <section aria-label="GO key metrics" className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{data.metrics.map((metric,index)=><MetricCard key={metric.key} metric={metric} accent={index%3}/>)}</section>
    <div className="grid gap-6 xl:grid-cols-[1.65fr_1fr]">
      <GoTrafficChart traffic={data.trafficSeries} conversions={data.conversionSeries}/>
      <GoServiceMix values={data.serviceMix}/>
    </div>
    <div className="grid gap-6 xl:grid-cols-[1fr_1fr_1fr]">
      <OperationalCard title="GO approval inbox" icon={CheckCircle2} tone="success"><p>News and newsletter items waiting for your approval.</p><Link href="/news" className="mt-4 inline-flex items-center gap-1 text-xs font-semibold text-primary hover:underline">Open editorial queue <ArrowRight className="size-3"/></Link></OperationalCard>
      <OperationalCard title="GO delivery posture" icon={Mail} tone="info"><p>Newsletter delivery, bounce, complaint, and suppression health.</p><Link href="/newsletters" className="mt-4 inline-flex items-center gap-1 text-xs font-semibold text-primary hover:underline">Open newsletter studio <ArrowRight className="size-3"/></Link></OperationalCard>
      <OperationalCard title="GO event pipeline" icon={Activity} tone="cyan"><p>Consent-aware landing, content, CTA, and campaign events feeding aggregates.</p><Link href="/analytics" className="mt-4 inline-flex items-center gap-1 text-xs font-semibold text-primary hover:underline">Inspect analytics <ArrowRight className="size-3"/></Link></OperationalCard>
    </div>
    <section className="overflow-hidden rounded-3xl border border-border bg-white shadow-[0_10px_28px_rgba(3,34,84,.06)]"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-border bg-gradient-to-r from-white to-[#f3f8ff] p-5"><div><h2 className="font-bold text-navy">GO operating signals</h2><p className="mt-1 text-xs text-muted">Live system context for publishing, audiences, and delivery</p></div><Link href="/health" className="inline-flex items-center gap-1 text-xs font-semibold text-primary hover:underline">System diagnostics <ArrowRight className="size-3"/></Link></div><div className="grid divide-y divide-border md:grid-cols-3 md:divide-x md:divide-y-0"><Signal icon={DatabaseZap} label="Database" value={data.status==="ready"||data.status==="empty"?"Connected":"Not connected"} tone={data.status==="ready"||data.status==="empty"?"success":"warning"}/><Signal icon={ShieldCheck} label="Email guard" value="Protected" tone="success"/><Signal icon={Clock3} label="Background jobs" value="Awaiting connection" tone="muted"/></div></section>
    <p className="flex items-center justify-center gap-2 text-center text-[11px] text-muted"><Download className="size-3"/> Metrics are sourced from versioned GO daily aggregates. No demo or finance data is displayed.</p>
  </div>;
}

function MetricCard({metric,accent}:{metric:OverviewMetric;accent:number}){const icon=metric.key.includes("newsletter")?Mail:metric.key.includes("news")?Newspaper:metric.key.includes("app")?Smartphone:metric.key.includes("gowash")?Utensils:metric.key.includes("gocarry")?UsersRound:metric.key.includes("delivery")?Mail:metric.key.includes("failed")?TriangleAlert:BarChart3;const Icon=icon;const value=metric.value===null?"—":metric.unit==="percent"?`${metric.value.toFixed(1)}%`:metric.value.toLocaleString();return <article className="group relative overflow-hidden rounded-3xl border border-border bg-white p-5 shadow-[0_4px_20px_rgba(9,95,199,.04)] transition hover:-translate-y-0.5 hover:shadow-[0_14px_30px_rgba(9,95,199,.1)]"><span className={`absolute inset-x-0 top-0 h-1 ${accent===0?"bg-primary":accent===1?"bg-cyan":"bg-[#9bb9df]"}`}/><div className="flex items-center justify-between"><div className="grid size-9 place-items-center rounded-xl bg-surface-subtle text-primary"><Icon className="size-4" aria-hidden="true"/></div><span className="text-[10px] font-semibold uppercase tracking-wider text-muted">GO metric</span></div><p className="mt-5 text-xs font-bold tracking-tight text-slate-700">{metric.label}</p><p className="mt-2 font-mono text-3xl font-bold tracking-tight text-navy" aria-label={`${metric.label}: ${metric.value===null?"not available":value}`}>{value}</p><p className="mt-2 text-[11px] leading-4 text-muted">{metric.definition}</p></article>}

function GoTrafficChart({traffic,conversions}:{traffic:(number|null)[];conversions:(number|null)[]}){const hasData=traffic.some((value)=>value!==null)||conversions.some((value)=>value!==null);const max=Math.max(...traffic.filter((value):value is number=>value!==null),...conversions.filter((value):value is number=>value!==null),1);return <section className="overflow-hidden rounded-3xl border border-border bg-white shadow-[0_10px_28px_rgba(3,34,84,.06)]"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-border bg-gradient-to-r from-white to-[#f3f8ff] p-5"><div><h2 className="font-bold text-navy">GO audience flow</h2><p className="mt-1 text-xs text-muted">Landing visits and confirmed newsletter joins by day</p></div><div className="flex items-center gap-4 text-[11px] font-semibold text-muted"><span className="flex items-center gap-1.5"><span className="size-2 rounded-full bg-primary"/>Landing visits</span><span className="flex items-center gap-1.5"><span className="size-2 rounded-full bg-cyan"/>Newsletter joins</span></div></div>{hasData?<div className="p-5"><div className="flex h-56 items-end gap-2 border-b border-border px-2 pb-0 sm:gap-4">{traffic.map((value,index)=><div key={index} className="flex h-full flex-1 items-end justify-center gap-1" aria-label={`Day ${index+1}: ${value??0} landing visits and ${conversions[index]??0} newsletter joins`}><span className="w-2.5 rounded-t-full bg-primary/90" style={{height:`${Math.max(((value??0)/max)*100,2)}%`}}/><span className="w-2.5 rounded-t-full bg-cyan/80" style={{height:`${Math.max(((conversions[index]??0)/max)*100,2)}%`}}/></div>)}</div><div className="mt-3 flex justify-between px-2 text-[10px] text-muted"><span>Earlier</span><span>Most recent</span></div></div>:<div className="grid min-h-64 place-items-center bg-[linear-gradient(rgba(3,34,84,.035)_1px,transparent_1px),linear-gradient(90deg,rgba(3,34,84,.035)_1px,transparent_1px)] bg-[size:28px_28px] p-8 text-center"><div className="rounded-2xl border border-white/80 bg-white/90 px-8 py-6 shadow-sm"><Activity className="mx-auto size-8 text-[#9aa9bc]"/><p className="mt-3 font-semibold text-navy">GO audience flow is ready</p><p className="mt-1 max-w-sm text-xs leading-5 text-muted">Connect the event pipeline and this chart will populate with real GO landing and newsletter activity.</p></div></div>}</section>}

function GoServiceMix({values}:{values:{label:string;value:number}[]}){const total=values.reduce((sum,item)=>sum+item.value,0);const first=total>0?(values[0]?.value??0)/total*100:0;const second=total>0?first+(values[1]?.value??0)/total*100:first;return <section className="overflow-hidden rounded-3xl border border-border bg-white shadow-[0_10px_28px_rgba(3,34,84,.06)]"><div className="border-b border-border bg-gradient-to-r from-white to-[#f3f8ff] p-5"><h2 className="font-bold text-navy">GO service interest</h2><p className="mt-1 text-xs text-muted">CTA engagement across GoWash, GoCarry, and the GO app</p></div>{total>0?<div className="p-6"><div className="mx-auto grid size-44 place-items-center rounded-full" style={{background:`conic-gradient(#095fc7 0 ${first}%,#3abfe0 ${first}% ${second}%,#9bb9df ${second}% 100%)`}}><div className="grid size-28 place-items-center rounded-full bg-white text-center"><span className="text-[10px] text-muted">Total interest</span><strong className="font-mono text-xl text-navy">{total.toLocaleString()}</strong></div></div><ul className="mt-6 space-y-3">{values.map((item,index)=><li key={item.label} className="flex items-center justify-between text-xs"><span className="flex items-center gap-2 font-medium text-slate-700"><span className={`size-2 rounded-full ${index===0?"bg-primary":index===1?"bg-cyan":"bg-[#9bb9df]"}`}/>{item.label}</span><strong className="font-mono text-navy">{item.value.toLocaleString()}</strong></li>)}</ul></div>:<div className="grid min-h-64 place-items-center p-8 text-center"><div><div className="mx-auto grid size-32 place-items-center rounded-full border-[14px] border-surface-subtle"><div className="text-center"><span className="block text-[10px] text-muted">GO services</span><strong className="font-mono text-lg text-navy">—</strong></div></div><p className="mt-5 text-xs leading-5 text-muted">GoWash, GoCarry, and app engagement will appear here as GO CTA events arrive.</p></div></div>}</section>}

function OperationalCard({title,icon:Icon,tone,children}:{title:string;icon:typeof Activity;tone:"success"|"info"|"cyan";children:React.ReactNode}){return <section className="rounded-3xl border border-border bg-white p-5 shadow-[0_8px_22px_rgba(3,34,84,.05)]"><div className="flex items-center gap-3"><div className={`grid size-9 place-items-center rounded-xl ${tone==="success"?"bg-emerald-50 text-emerald-600":tone==="info"?"bg-blue-50 text-primary":"bg-cyan/10 text-[#168ba8]"}`}><Icon className="size-4"/></div><h2 className="font-bold text-navy">{title}</h2></div><div className="mt-4 border-t border-border pt-4 text-xs leading-5 text-muted">{children}</div></section>}
function Signal({icon:Icon,label,value,tone}:{icon:typeof Activity;label:string;value:string;tone:"success"|"warning"|"muted"}){return <div className="flex items-center gap-3 p-5"><Icon className={`size-4 ${tone==="success"?"text-emerald-600":tone==="warning"?"text-warning":"text-muted"}`}/><span className="text-xs font-medium text-slate-700">{label}</span><span className={`ml-auto text-xs font-semibold ${tone==="success"?"text-emerald-600":tone==="warning"?"text-warning":"text-muted"}`}>{value}</span></div>}
