"use client";
import {useCallback,useEffect,useRef,useState} from "react";
import {ArrowLeft,Check,Mail,RefreshCw} from "lucide-react";
import {OTP_RESEND_SECONDS} from "@/lib/auth/otp";
const DIGITS=6,ORBIT_MS=800,SUCCESS_HOLD_MS=700;
type Stage="email"|"code"|"success"; type Notice={message:string;kind:"error"|"info"}|null;
const maskEmail=(email:string)=>{const [local,domain]=email.split("@");return local&&domain?`${local[0]}${"*".repeat(Math.max(2,Math.min(5,local.length-1)))}@${domain}`:email};
export function LoginForm({next="/"}:{next?:string}){
 const [stage,setStage]=useState<Stage>("email"),[email,setEmail]=useState(""),[code,setCode]=useState<string[]>(Array(DIGITS).fill("")),[pending,setPending]=useState(false),[resendIn,setResendIn]=useState(0),[notice,setNotice]=useState<Notice>(null);
 const inputs=useRef<Array<HTMLInputElement|null>>([]),orbit=useRef<Array<HTMLSpanElement|null>>([]),area=useRef<HTMLDivElement>(null),submitted=useRef(false);
  const requestCode=useCallback(async()=>{setPending(true);setNotice(null);try{const r=await fetch("/api/auth/otp/request",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email})}),b=await r.json();if(!r.ok){if(r.status===429&&typeof b.retryAfter==="number"){setStage("code");setResendIn(b.retryAfter);setNotice({kind:"info",message:`A code was already sent. Enter it above, or resend in ${b.retryAfter}s.`});setTimeout(()=>inputs.current[0]?.focus(),40)}else throw new Error(b.error)}else{setStage("code");setCode(Array(DIGITS).fill(""));setResendIn(OTP_RESEND_SECONDS);setNotice({kind:"info",message:"A verification code is on its way."});setTimeout(()=>inputs.current[0]?.focus(),40)}}catch(e){setNotice({kind:"error",message:e instanceof Error?e.message:"Unable to send code."})}finally{setPending(false)}},[email]);
 useEffect(()=>{if(!resendIn)return;const id=setInterval(()=>setResendIn(v=>Math.max(0,v-1)),1000);return()=>clearInterval(id)},[resendIn]);
 const verify=useCallback(async(value:string[])=>{if(submitted.current||value.join("").length<DIGITS)return;submitted.current=true;setPending(true);setNotice(null);try{const r=await fetch("/api/auth/otp/verify",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email,code:value.join(""),next})}),b=await r.json();if(!r.ok)throw new Error(b.error);setStage("success");const box=area.current;if(box&&!window.matchMedia("(prefers-reduced-motion: reduce)").matches){const rect=box.getBoundingClientRect(),radius=Math.min(rect.width,rect.height)*.32;orbit.current.forEach((node,i)=>{if(!node)return;const angle=(i*360/DIGITS-90)*Math.PI/180,dx=Math.cos(angle)*radius,dy=Math.sin(angle)*radius;node.style.transformOrigin=`${rect.width/2}px ${rect.height/2}px`;node.animate([{transform:`translate(${dx}px,${dy}px) rotate(0deg)`,opacity:1},{transform:"translate(0,0) rotate(450deg)",opacity:0}],{duration:ORBIT_MS,easing:"cubic-bezier(.15,.85,.25,1)",fill:"forwards"})})}setTimeout(()=>window.location.assign(b.redirectUrl),SUCCESS_HOLD_MS+ORBIT_MS)}catch(e){submitted.current=false;setCode(Array(DIGITS).fill(""));setPending(false);setNotice({kind:"error",message:e instanceof Error?e.message:"Incorrect code."});setTimeout(()=>inputs.current[0]?.focus(),30)}},[email,next]);
 function digit(i:number,value:string){const nextCode=[...code];nextCode[i]=value.replace(/\D/g,"").slice(-1);setCode(nextCode);if(nextCode[i]&&i<DIGITS-1)inputs.current[i+1]?.focus();if(nextCode.every(Boolean))void verify(nextCode)}
 function paste(e:React.ClipboardEvent){e.preventDefault();const value=e.clipboardData.getData("text").replace(/\D/g,"").slice(0,DIGITS),nextCode=Array(DIGITS).fill("").map((_,i)=>value[i]??"");setCode(nextCode);if(value.length===DIGITS)void verify(nextCode)}
 return <div className="login-card"><div className="login-brand"><span className="login-logo">GO</span><div><p className="login-brand-name">GO Admin</p><p className="login-brand-caption">Secure operations console</p></div></div>{stage==="success"?<Success code={code} orbit={orbit} area={area}/>:stage==="email"?<form className="login-form" onSubmit={e=>{e.preventDefault();if(!pending)void requestCode()}}><div><p className="login-eyebrow">Welcome back</p><h1>Admin sign in</h1><p className="login-subtitle">Use your authorized work email to continue.</p></div><label className="login-label" htmlFor="admin-email">Work email<div className="login-input-wrap"><Mail size={18}/><input id="admin-email" type="email" required autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@go.example"/></div></label>{notice&&<p className={`login-notice ${notice.kind}`} role={notice.kind==="error"?"alert":"status"}>{notice.message}</p>}<button className="login-submit" disabled={pending}>{pending?<><RefreshCw className="spin" size={17}/>Sending code…</>:"Send code"}</button><p className="login-footnote">Access is limited to invited GO team members.</p></form>:<div className="login-form"><button className="login-back" type="button" onClick={()=>{setStage("email");setNotice(null)}}><ArrowLeft size={16}/>Use a different email</button><div><p className="login-eyebrow">One more step</p><h1>Verify your email</h1><p className="login-subtitle">Enter the 6-digit code we sent to <strong>{maskEmail(email)}</strong></p></div><div className="otp-grid" onPaste={paste}>{code.map((value,i)=><input key={i} ref={node=>{inputs.current[i]=node}} value={value} maxLength={1} inputMode="numeric" autoComplete={i===0?"one-time-code":"off"} aria-label={`Digit ${i+1} of 6`} onChange={e=>digit(i,e.target.value)} onKeyDown={e=>{if(e.key==="Backspace"&&!code[i]&&i>0)inputs.current[i-1]?.focus()}}/>)}</div>{notice&&<p className={`login-notice ${notice.kind}`} role="alert">{notice.message}</p>}<p className="resend-row">Didn’t receive the code? {resendIn?<span>Resend in {resendIn}s</span>:<button type="button" disabled={pending} onClick={()=>void requestCode()}>Resend</button>}</p></div>}</div>;
}
function Success({code,orbit,area}:{code:string[];orbit:React.MutableRefObject<Array<HTMLSpanElement|null>>;area:React.RefObject<HTMLDivElement|null>}){return <div className="login-success" aria-live="polite"><div className="orbit-area" ref={area}><svg className="orbit-guide" viewBox="0 0 220 220" aria-hidden="true"><circle cx="110" cy="110" r="72"/></svg><span className="orbit-hub"/>{code.map((value,i)=><span className="orbit-digit" ref={node=>{orbit.current[i]=node}} key={i}>{value}</span>)}<span className="success-badge"><Check size={25}/></span>{Array.from({length:23},(_,i)=><span className="ripple" style={{animationDelay:`${i*35}ms`}} key={`r${i}`}/>)}{Array.from({length:14},(_,i)=><span className="particle" data-index={i} style={{animationDelay:`${i*18}ms`}} key={`p${i}`}/>)}</div><h1>Verified successfully</h1><p className="login-subtitle">Your account has been verified.</p></div>}
